"""Shared prompt version tags and token limits."""

PERCEPTION_PROMPT_VERSION = "scope2-v11"
SCREEN_PERCEPTION_PROMPT_VERSION = "screen-v4"
PERCEPTION_MAX_OUTPUT_TOKENS = 4096
GEMINI_MIN_VIDEO_DURATION_MS = 1_500
DEFAULT_GEMINI_FLASH_MODEL = "gemini-3-flash-preview"
DEFAULT_GEMINI_PRO_MODEL = "gemini-3.1-pro-preview"
PERCEPTION_ASSEMBLY_LOGIC_VERSION = "assembly-v2-merge-observations-by-window"
PERCEPTION_MODEL_VERSION = DEFAULT_GEMINI_FLASH_MODEL
