"""Canonical MachineFact kind registry (Scope 1 vocabulary)."""

from enum import StrEnum


class MachineFactKind(StrEnum):
    FACE_NOT_VISIBLE_WARNING = "FACE_NOT_VISIBLE_WARNING"
    FACE_WARNING_DISMISSED = "FACE_WARNING_DISMISSED"
    CAMERA_BLOCKED = "CAMERA_BLOCKED"
    MULTIPLE_FACES = "multiple_faces"
    MOVED_OUT_OF_WINDOW = "incident.moved_out_of_window"
    TAB_SWITCH = "TAB_SWITCH"
    WINDOW_BLUR = "WINDOW_BLUR"
    WINDOW_FOCUS = "WINDOW_FOCUS"
    FULLSCREEN_EXIT = "FULLSCREEN_EXIT"
    COPY = "COPY"
    PASTE = "PASTE"
    LARGE_TEXT_INSERTION = "LARGE_TEXT_INSERTION"
    MIC_DISABLED = "MIC_DISABLED"
    SECOND_MONITOR_DETECTED = "SECOND_MONITOR_DETECTED"
    NOISE_DETECTED = "NOISE_DETECTED"
    ACTIVITY_GAP = "ACTIVITY_GAP"
    TYPING_STARTED = "TYPING_STARTED"
    TYPING_STOPPED = "TYPING_STOPPED"
    LARGE_PASTE = "LARGE_PASTE"
    TEXT_CORRECTION = "TEXT_CORRECTION"
    RIGHT_CLICK = "RIGHT_CLICK"
    ASSESSMENT_STARTED = "ASSESSMENT_STARTED"
    ALL_SECTIONS_COMPLETED = "ALL_SECTIONS_COMPLETED"
    SECTION_STARTED = "SECTION_STARTED"
    SECTION_COMPLETED = "SECTION_COMPLETED"
    SECTION_TERMINATED = "SECTION_TERMINATED"
    SECTION_TIMEOUT = "SECTION_TIMEOUT"
    SECTION_QUIT_BY_USER = "SECTION_QUIT_BY_USER"
    MCQ_ANSWER_SELECTED = "MCQ_ANSWER_SELECTED"
    MCQ_ANSWER_CHANGED = "MCQ_ANSWER_CHANGED"
    AUTOFORMAT = "AUTOFORMAT"
    QUESTION_ENTERED = "QUESTION_ENTERED"
    QUESTION_EXITED = "QUESTION_EXITED"
    ANSWER_SUBMITTED = "ANSWER_SUBMITTED"
    SECTION_SCORE = "SECTION_SCORE"
    QUESTION_ATTEMPTED = "QUESTION_ATTEMPTED"
    CODE_SUBMISSION = "CODE_SUBMISSION"
    DIFFICULTY_BAND_SCORE = "DIFFICULTY_BAND_SCORE"
    PLAGIARISM_MATCH = "PLAGIARISM_MATCH"
    TEST_RESULT_OBSERVED = "TEST_RESULT_OBSERVED"
    SCREEN_EXTERNAL_PASTE = "SCREEN_EXTERNAL_PASTE"
    SCREEN_EXTERNAL_RESOURCE = "SCREEN_EXTERNAL_RESOURCE"
    SCREEN_AI_ASSISTANT_UI = "SCREEN_AI_ASSISTANT_UI"
    SCREEN_SECONDARY_WORKSPACE = "SCREEN_SECONDARY_WORKSPACE"
    SCREEN_FULLSCREEN_LOST = "SCREEN_FULLSCREEN_LOST"
    UNKNOWN = "UNKNOWN"


LIFECYCLE_KIND_MAP: dict[str, MachineFactKind] = {
    "ASSESSMENT_STARTED": MachineFactKind.ASSESSMENT_STARTED,
    "ALL_SECTIONS_COMPLETED": MachineFactKind.ALL_SECTIONS_COMPLETED,
    "SECTION_STARTED": MachineFactKind.SECTION_STARTED,
    "SECTION_COMPLETED": MachineFactKind.SECTION_COMPLETED,
    "SECTION_TERMINATED": MachineFactKind.SECTION_TERMINATED,
    "SECTION_TIMEOUT": MachineFactKind.SECTION_TIMEOUT,
    "SECTION_QUIT_BY_USER": MachineFactKind.SECTION_QUIT_BY_USER,
}
